package dao;

import model.BaseUser;

public interface BaseUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_user
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_user
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    int insert(BaseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_user
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    int insertSelective(BaseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_user
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    BaseUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_user
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    int updateByPrimaryKeySelective(BaseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dh_user
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    int updateByPrimaryKey(BaseUser record);
}