package model;

import java.util.Date;

public class BaseUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_user.id
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_user.organization_id
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    private Integer organizationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_user.username
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_user.password
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_user.status
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_user.type
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_user.age
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_user.fullname
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    private String fullname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_user.gender
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_user.email
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_user.phone
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_user.image
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_user.create_time
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_user.is_delete
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    private Byte isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_user.delete_time
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    private Date deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_user.last_login_time
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dh_user.last_login_ip
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    private String lastLoginIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_user.id
     *
     * @return the value of dh_user.id
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_user.id
     *
     * @param id the value for dh_user.id
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_user.organization_id
     *
     * @return the value of dh_user.organization_id
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public Integer getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_user.organization_id
     *
     * @param organizationId the value for dh_user.organization_id
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public void setOrganizationId(Integer organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_user.username
     *
     * @return the value of dh_user.username
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_user.username
     *
     * @param username the value for dh_user.username
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_user.password
     *
     * @return the value of dh_user.password
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_user.password
     *
     * @param password the value for dh_user.password
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_user.status
     *
     * @return the value of dh_user.status
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_user.status
     *
     * @param status the value for dh_user.status
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_user.type
     *
     * @return the value of dh_user.type
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_user.type
     *
     * @param type the value for dh_user.type
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_user.age
     *
     * @return the value of dh_user.age
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_user.age
     *
     * @param age the value for dh_user.age
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_user.fullname
     *
     * @return the value of dh_user.fullname
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_user.fullname
     *
     * @param fullname the value for dh_user.fullname
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_user.gender
     *
     * @return the value of dh_user.gender
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_user.gender
     *
     * @param gender the value for dh_user.gender
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_user.email
     *
     * @return the value of dh_user.email
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_user.email
     *
     * @param email the value for dh_user.email
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_user.phone
     *
     * @return the value of dh_user.phone
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_user.phone
     *
     * @param phone the value for dh_user.phone
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_user.image
     *
     * @return the value of dh_user.image
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_user.image
     *
     * @param image the value for dh_user.image
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_user.create_time
     *
     * @return the value of dh_user.create_time
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_user.create_time
     *
     * @param createTime the value for dh_user.create_time
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_user.is_delete
     *
     * @return the value of dh_user.is_delete
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_user.is_delete
     *
     * @param isDelete the value for dh_user.is_delete
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_user.delete_time
     *
     * @return the value of dh_user.delete_time
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_user.delete_time
     *
     * @param deleteTime the value for dh_user.delete_time
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_user.last_login_time
     *
     * @return the value of dh_user.last_login_time
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_user.last_login_time
     *
     * @param lastLoginTime the value for dh_user.last_login_time
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dh_user.last_login_ip
     *
     * @return the value of dh_user.last_login_ip
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dh_user.last_login_ip
     *
     * @param lastLoginIp the value for dh_user.last_login_ip
     *
     * @mbg.generated Fri Dec 01 17:27:30 CST 2017
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }
}